name: Conflict Explainer

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  explain-conflicts:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Check out PR head
        uses: actions/checkout@v4
        with:
          # Fetch full history so git can attempt merges
          fetch-depth: 0
          # Check out the PR head sha
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm init -y
          npm pkg set type="module"
          npm install openai@^4.0.0
        working-directory: ./

      - name: Run conflict explainer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: node scripts/explain-conflicts.js
